name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: add custom deb repository
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
        repo-name: sources
    - name: Install build dependencies
      run: |
        sudo apt-get update -y && sudo apt-get -y build-dep gnumeric && sudo apt-get -y install gtk-doc-tools yelp yelp-tools
    - run: make mybuild
    - name: Configure
      run: |
        ./autogen.sh
    - name: Configure
      run: |
        ./configure --prefix=/home/runner/work/gnumeric/mybuild
    - name: Make
      run: |
        make
    - name: Make install
      run: |
        make install
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: mybuild