name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: add custom deb repository
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb-src http://azure.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
        repo-name: sources
    - name: Install build dependencies
      run: |
        sudo apt-get update -y && sudo apt-get -y build-dep gnumeric && sudo apt-get -y install gtk-doc-tools yelp yelp-tools
    - name: Configure
      run: |
        ./autogen.sh
    - name: Configure
      run: |
        ./configure
    - name: Make
      run: |
        make

