name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: add custom deb repository
      uses: myci-actions/add-deb-repo@10
      with:
        repo: deb-src http://azure.archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
        repo-name: sources
    - name: Install build dependencies
      run: sudo apt-get update -y && sudo apt-get -y build-dep gnumeric && sudo apt-get -y install gtk-doc-tools yelp yelp-tools
    - run: mkdir mybuild
    - name: Autogen
      run: ./autogen.sh
    - name: Configure
      run: ./configure --prefix=$PWD/mybuild
    - name: Make
      run: make
    - name: Make install to a local directory
      run: sudo make install
    - run: echo 'LD_LIBRARY_PATH=$PWD/lib ./bin/gnumeric' > $PWD/mybuild/run.sh
    - run: chmod +x $PWD/mybuild/run.sh
    - name: Tar files to preserve file permissions
      run: tar -cvf my-gnumeric-build.tar mybuild
    - name: Upload built Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-gnumeric-build
        path: my-gnumeric-build.tar
